---
title: "CorrelaciónLineal"
author: "Adrián R"
date: "2024-02-28"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Correlación Lineal

```{r echo = T}
library(readxl)
data = as.data.frame(read_excel('C:/CorrelaciónLineal/data.xlsx'))

data
```

```{r}
panel.cor <- function(x, y, digits = 2, prefix = "", cex.cor, ...) {
  usr <- par ("usr")
  on.exit(par("usr"))
  par(usr= c(0, 1, 0, 1))
  Cor <- abs(cor(x, y))
  txt <- paste0(prefix, format(c(Cor, 0.123456789), digits = digits)[1])
  if(missing(cex.cor)) {
    cex.cor = 0.4 / strwidth(txt)
  }
  text(0.5, 0.5, txt,
       cex = 1+ cex.cor * Cor) 
}
pairs(data,
      upper.panel = panel.cor,
      lower.panel = panel.smooth)
```
``` {r echo=TRUE}
cor.test(data$longitud, data$peso)
```
```{r warning=FALSE}
library(correlation)
resultados <- correlation(data)
resultados
```
```{r echo=TRUE}
library(ggpubr)
ggscatter(data, x = "longitud", y = "peso",
          add = "reg.line", conf.int = TRUE,
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Longitud piezas (mm)", ylab = "Peso piezas (mg)")
```
```{r }
library(corrplot)
corrplot(cor(data))
```
```{r }
corrplot.mixed(cor(data))
```
```{r}
distancia <- c(1.1, 100.2, 90.3, 5.4, 57.5, 6.6, 34.7, 65.8, 57.9, 86.1)
n_piezas <- c(110, 2, 6, 98, 40, 94, 31, 5, 8, 10)
dist_ncuent <- data.frame(distancia, n_piezas)
knitr::kable(dist_ncuent)
```
#CALCULA EL COEFICIENTE DE CORRELACIÓN.
```{r warning = FALSE}
library(correlation)
resultado <- correlation(dist_ncuent)
resultado
```
#CALCULA EL NIVEL DE SIGNIFICANCIA
```{r echo = TRUE}
cor.test(dist_ncuent$distancia, dist_ncuent$n_piezas)
```
#INTERVALO DE CONFIANZA AL 95% EN RELACIÓN CON EL COEFICIENTE DE CORRELACIÓN.
El margen de error es relativamente muy bajo.

#¿QUÉ INTENSIDAD Y DIRECCIÓN PRESENTAN AMBAS VARIABLES?
```{r echo=TRUE}
library(ggpubr)
ggscatter(dist_ncuent, x = "distancia", y = "n_piezas",
          add = "reg.line", conf.int = TRUE,
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Distancia", ylab = "n_piezas")
```
#¿ES SIGNIFICATIVA ESTA RELACIÓN?
Sí.



